### ISSUE TITLE
New major release: 3.0.0

### ISSUE THREAD

**Issue by sapegin** [sapegin/mrm#135]
There are several significant changes in this release:

- [x] Tasks and preset autoinstall #99
- [x] Deprecate the default preset and remove it as a dependency from the `mrm` package in favor of autoinstall  #136
- [x] Migrate all tasks to the new config API, based on Inquirer (there's one task left — `gitter`) #137
- [x] Remove the old config API #139
- [x] Drop Node.js 8 support #138
- [ ] Revise docs

**Comment by brettz9** [comment]
Would it be too much trouble to get my testing PRs merged (#128, #129, #130; I guess #131 will not be needed if the old config API is merged). I can wait on #99 (task autoinstall) and rebase these tests (or possibly help rebase that one). I think having these could help provide assurances on other changes not causing breakage.

**Comment by sapegin** [comment]
They are pretty large — I don't know when I'll have time to look ;-/

**Comment by frontsideair** [comment]
Clarification, as mentioned on #99 that PR includes preset autoinstallation.

**Comment by brettz9** [comment]
@sapegin : Ok. Let me know if breaking up #129 would help .

**Comment by sapegin** [comment]
@frontsideair great! Updated the list ;-)

**Comment by frontsideair** [comment]
@sapegin what should be the minimum supported node version? It's currently `>=8.9`, which is the lowest LTS version in 8. The next LTS, according to [nodejs.org](https://nodejs.org/en/download/releases/) is 10 so it should be `>=10.13.0` if I'm not missing anything.

**Comment by frontsideair** [comment]
I had a bit of free time and opened PRs for all remaining tasks. Let me know if there's any more work left as I'm eager to ship autoinstall. 😄

**Comment by sapegin** [comment]
@frontsideair This is awesome, thank you! I'll have a look if we need to update the docs, and make a beta release soon.

**Comment by frontsideair** [comment]
I went through the docs and found one reference to the global installation of tasks, but it's not on `next` branch as it was also fixed with #99. The note about old config was removed with #139. I may have missed something so another look is always welcome.

**Comment by frontsideair** [comment]
Anything I can do to help move the release forward?

**Comment by sapegin** [comment]
Well, I merged the `next` branch into `master` and it published some packages — I hope it works ;-)

**Comment by sapegin** [comment]
I've also marked `mrm-preset-default` 3.0.0 as deprecated on npm.

**Comment by sapegin** [comment]
And looks like something is broken in Node.js 10:

```
FAIL packages/mrm/src/__tests__/index.spec.js (18.403s)
  ● runTask › should throw when module not found
    expect(received).rejects.toHaveProperty(path, value)
    Expected path: "message"
    Expected value: "Task “pizza” not found."
    Received value: "Cannot read property 'width' of undefined"
      338 | 		// ideally we can use toThrowError but that works with >= jest@22
      339 | 		// https://github.com/facebook/jest/issues/5076
    > 340 | 		return expect(pizza).rejects.toHaveProperty(
          | 		                             ^
      341 | 			'message',
      342 | 			'Task “pizza” not found.'
      343 | 		);
      at Object.toHaveProperty (node_modules/expect/build/index.js:242:20)
      at Object.it (packages/mrm/src/__tests__/index.spec.js:340:32)
```

https://travis-ci.org/github/sapegin/mrm/jobs/766192897

**Comment by frontsideair** [comment]
I don't know why this code throws a "Cannot read property 'width' of undefined" error or why it's happening only on Node 10, but since we're now trying to load a package with `npx` and `pizza` is a package that exists, I renamed the package name and in my local tests this seems to fix it.

**Comment by frontsideair** [comment]
When testing the new version locally I found an error because we assume the default preset is installed by default. With the default preset deprecated we should clean the code of all traces.

I'll have a priority fix for the error soon and can look into cleanup later.
